package org.p2p.wallet.striga.user.model

import java.time.ZonedDateTime
import org.p2p.core.utils.MillisSinceEpoch

data class StrigaUserDetails(
    val userId: String,
    val createdAt: MillisSinceEpoch,
    val userInfo: StrigaUserInfo,
    val addressDetails: StrigaUserAddress,
    val kycDetails: StrigaUserKycInfo
)

class StrigaUserInfo(
    val firstName: String,
    val lastName: String,
    val dateOfBirth: ZonedDateTime,
    val nationality: String,
    val email: String,
    val phoneNumber: String,
    val phoneNumberCode: String,
    val placeOfBirth: String,
)

data class StrigaUserAddress(
    val addressLine1: String,
    val addressLine2: String,
    val city: String,
    val state: String,
    val country: String,
    val postalCode: String
)

/**
 * @property rejectionUserToAutoComments
 * (first - KYC rejection comment for the user from the compliance team)
 * (second - KYC rejection comment generated by the system)
 * @property rejectionDetails Details on why the KYC failed, if it did
 */
data class StrigaUserKycInfo(
    val occupation: String,
    val sourceOfFunds: String,
    val purposeOfAccount: String,
    val isEmailVerified: Boolean,
    val isMobileVerified: Boolean,
    val kycStatus: StrigaUserVerificationStatus,
    val rejectionDetails: List<String> = emptyList(),
    val rejectionUserToAutoComments: Pair<String, String>
)
