name: "Generate changelog"
description: "Getting commits from last commit hash to current one"

runs:
  using: composite
  steps:
    - name: "Find last commit hash and current one"
      shell: bash
      run: |
        # Get the latest commit hash was saved in last_commit_hash.txt
        last_commit_hash=$(cat last_commit_hash.txt)
        
        github_sha=${{ github.sha }}
        
        last_branch=$GITHUB_REF_NAME
        last_commit="$(git rev-parse $last_branch)"
        
        echo "data ${last_branch} ${last_commit} ${github_sha}"
        
        # Get the current head commit hash
        current_commit_hash="$(git rev-parse $last_branch)"
        
        echo "data ${current_commit_hash}"
        
        # Run the gradle task with the fromCommit and toCommit properties set
        ./gradlew gitChangelogTask -PfromCommit=$last_commit_hash -PtoCommit=$current_commit_hash