name: "Generate changelog"
description: "Getting commits from last commit hash to current one"

runs:
  using: composite
  steps:
    - name: "Find last commit hash and current one"
      shell: bash
      run: |
        # Get the latest commit hash was saved in last_commit_hash.txt
        last_commit_hash=$(cat last_commit_hash.txt)
        
        github_sha=${{ github.sha }}
        
        last_branch=${{ github.ref }}
        last_commit="$(git rev-parse $last_branch)"
        
        echo "GGG github sha: $github_sha $last_branch $last_commit"
        
        # Get the current head commit hash
        current_commit_hash="$(git rev-parse $github_sha)"
        
        # Run the gradle task with the fromCommit and toCommit properties set
        ./gradlew gitChangelogTask -PfromCommit=$last_commit_hash -PtoCommit=$current_commit_hash