name: "Generate changelog"
description: "Getting commits from last commit hash to current one"

runs:
  using: composite
  steps:
    - name: "Find last commit hash and current one"
      shell: bash
      run: |
        # Get the latest commit hash was saved in last_commit_hash.txt
        last_commit_hash=$(cat last_commit_hash.txt)
        
        github_sha=${{ github.sha }}
        
        echo "Branch: $GITHUB_HEAD_REF"
        echo "Commit: $(git log -1 --pretty=%B)"
        echo "SHA: $(git rev-parse HEAD)"
        
        # Determine the current head commit hash
        if [ -n "$GITHUB_HEAD_REF" ]; then
          # This is a pull request, use GITHUB_HEAD_REF
          current_commit_hash="$(git rev-parse "$GITHUB_HEAD_REF")"
        else
          # This is not a pull request, use GITHUB_BASE_REF
          current_commit_hash="$(git rev-parse "$GITHUB_BASE_REF")"
        fi
        
        echo "current_commit_hash: $current_commit_hash"
        echo "current_commit_hash2: $(git rev-parse "$GITHUB_BASE_REF")"
        
        # Run the gradle task with the fromCommit and toCommit properties set
        ./gradlew gitChangelogTask -PfromCommit=$last_commit_hash -PtoCommit=$current_commit_hash