name: "Generate changelog"
description: "Getting commits from last commit hash to current one"

inputs:
  current-ref-name:
    description: "We are getting different hash commits for PRs and develop changelog. develop or feature/*."
    required: true
  workflow-type:
    description: "According to workflow type, it will generate different last_commit_hash"
    required: false

runs:
  using: composite
  steps:
    - name: "Find last commit hash and current one"
      shell: bash
      run: |
        # Pull changes from the remote repository and merge them into the current branch
        git pull
        
        type=${{ inputs.workflow-type }}
        
        current_ref=${{ inputs.current-ref-name }}
        
        if [[ $type == "scheduled" ]]; then
          # Get the commit hash from the last night
          last_commit_hash=$(git rev-list -n 1 --before="yesterday 00:00" origin/$current_ref)
        else
          # Get the latest commit hash was saved in LastCommit.kt
          last_commit_hash=$(cd $GITHUB_WORKSPACE && sed -n 's/^ *const *val *COMMIT_HASH *= *"\(.*\)".*$/\1/p' buildSrc/src/main/java/LastCommit.kt)
        fi
        
        # Fetch the latest changes from the remote repository
        git fetch origin
        
        # Determine the current head commit hash
        current_commit_hash="$(git log -n 1 --pretty=%H origin/$current_ref)"
        
        # Run the gradle task with the fromCommit and toCommit properties set
        ./gradlew gitChangelogTask -PfromCommit=$last_commit_hash -PtoCommit=$current_commit_hash