name: "Commit and push changes"
description: "Commit and push changes which are made within the workflow"

inputs:
  github-commit-message:
    description: "Github commit message"
    required: false
    default: "Bump version"
  github-author-email:
    description: "Github author email"
    required: true
  admin-access-token:
    description: "Github access token with admin permissions"
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push changes
      shell: bash
      run: |
        git config user.name 'key-app-bot'
        git config user.email '${{ inputs.github-author-email }}'
        git commit -am "${{ inputs.github-commit-message }}"
        token=${{ inputs.admin-access-token }}
        git push https://$token@github.com/p2p-org/key-app-android.git HEAD:develop