name: "Commit and push changes"
description: "Commit and push changes which are made within the workflow"

inputs:
  github-commit-message:
    description: "Github commit message"
    required: false
    default: "Bump version"
  github-author-email:
    description: "Github author email"
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push changes
      shell: bash
      run: |
        git config --global user.name 'key-app-bot`'
        git config --global user.email '${{ inputs.github-author-email }}'
        git commit -am "${{ inputs.github-commit-message }}"
        git push