name: "Commit and push changes"
description: "Commit and push changes which are made within the workflow"

inputs:
  github-commit-message:
    description: "Github commit message"
    required: false
    default: "[CI-processing] - Bump version"
  github-author-name:
    description: "Github author email"
    required: false
    default: "key-app-bot"
  github-author-email:
    description: "Github author email"
    required: true
  github-access-token:
    description: "Github access token"
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push changes
      shell: bash
      run: |
        git config user.name '${{ inputs.github-author-name }}'
        git config user.email '${{ inputs.github-author-email }}'
        git commit -am "${{ inputs.github-commit-message }}"
        git remote set-url origin https://x-access-token:${{ inputs.github-access-token }}@github.com/p2p-org/key-app-android.git
        git push -u origin ${{ github.ref }}