package org.p2p.solanaj.core

import com.google.firebase.crashlytics.buildtools.reloc.com.google.common.base.Joiner
import com.google.firebase.crashlytics.buildtools.reloc.com.google.common.base.Stopwatch
import org.bitcoinj.crypto.DeterministicHierarchy
import org.bitcoinj.crypto.HDKeyDerivation
import org.bitcoinj.crypto.HDUtils
import org.bitcoinj.crypto.PBKDF2SHA512
import org.p2p.core.utils.emptyString
import org.p2p.solanaj.crypto.DerivationPath
import org.p2p.solanaj.crypto.SolanaBip44
import org.p2p.solanaj.utils.TweetNaclFast
import org.p2p.core.utils.Base58Utils

private const val PBKDF2_ROUNDS = 2048

class Account {
    private var keyPair: TweetNaclFast.Signature.KeyPair

    constructor() {
        keyPair = TweetNaclFast.Signature.keyPair()
    }

    constructor(keyPair: ByteArray) {
        this.keyPair = TweetNaclFast.Signature.keyPair_fromSecretKey(keyPair)
    }

    constructor(keypair: String) {
        this.keyPair = TweetNaclFast.Signature.keyPair_fromSecretKey(Base58Utils.decode(keypair))
    }

    private constructor(keyPair: TweetNaclFast.Signature.KeyPair) {
        this.keyPair = keyPair
    }

    /**
     * Returns an encoded [keyPair] in Base58
     * */
    fun getEncodedKeyPair(): String =
        Base58Utils.encode(keypair)

    val publicKey: PublicKey
        get() = PublicKey(keyPair.publicKey)

    /**
     * The secret key is 32 byte array
     *
     * The keypair is 64 byte array which consists of encoded secret key and public key
     * */
    val keypair: ByteArray
        get() = keyPair.secretKey

    companion object {
        /**
         * Derive a Solana account from a Mnemonic generated
         * by the Solana CLI using bip32 Mnemonic with deviation path of
         * m/501H/0H/0/0
         * @param words seed words
         * @param passphrase seed passphrase
         * @return Solana account
         */
        fun fromBip32Mnemonic(
            words: List<String>,
            walletIndex: Int,
            saltPrefix: String = "mnemonic",
            includeSpaces: Boolean = true,
            passphrase: String = emptyString()
        ): Account = try {
            val seed = toSeed(words, saltPrefix, passphrase, includeSpaces)
            val masterPrivateKey = HDKeyDerivation.createMasterPrivateKey(seed)
            val deterministicHierarchy = DeterministicHierarchy(masterPrivateKey)
            val child = deterministicHierarchy[HDUtils.parsePath("M/501H/${walletIndex}H/0/0"), true, true]
            val keyPair = TweetNaclFast.Signature.keyPair_fromSeed(child.privKeyBytes)
            Account(keyPair)
        } catch (error: Throwable) {
            throw AccountCreationFailed("BIP32", error)
        }

        /**
         * Derive a Solana account from a Mnemonic generated by the Solana CLI
         * using bip44 Mnemonic with derivation path
         * @param words seed words
         * @param passphrase seed passphrase
         * @param derivationPath
         * @return Solana account
         */
        @Throws(AccountCreationFailed::class)
        fun fromBip44Mnemonic(
            words: List<String>,
            walletIndex: Int,
            derivationPath: DerivationPath,
            saltPrefix: String = "mnemonic",
            passphrase: String = emptyString(),
            includeSpaces: Boolean = true
        ): Account {
            return try {
                require(derivationPath != DerivationPath.BIP32DEPRECATED) {
                    "Incorrect derivation path for this method: $derivationPath"
                }

                val solanaBip44 = SolanaBip44(walletIndex)
                val seed: ByteArray = toSeed(
                    words = words,
                    saltPrefix = saltPrefix,
                    passphrase = passphrase,
                    includeSpaces = includeSpaces
                )
                val privateKey: ByteArray = solanaBip44.getPrivateKeyFromSeed(seed, derivationPath)
                Account(TweetNaclFast.Signature.keyPair_fromSeed(privateKey))
            } catch (error: Throwable) {
                throw AccountCreationFailed(derivationPath.stringValue, error)
            }
        }

        private fun toSeed(
            words: List<String>,
            saltPrefix: String,
            passphrase: String,
            includeSpaces: Boolean
        ): ByteArray {
            val seedPhrase = if (includeSpaces) {
                Joiner.on(" ").join(words)
            } else {
                buildString { words.forEach(::append) }
            }

            return toSeedPhrase(seedPhrase, saltPrefix, passphrase)
        }

        private fun toSeedPhrase(seedPhrase: String, saltPrefix: String = "mnemonic", passphrase: String): ByteArray {
            require(seedPhrase.isNotBlank()) {
                "Passed seed phrase is empty!"
            }
            val salt = "$saltPrefix$passphrase"
            val watch: Stopwatch = Stopwatch.createStarted()

            val seed = PBKDF2SHA512.derive(
                seedPhrase,
                salt,
                PBKDF2_ROUNDS,
                64
            )
            watch.stop()
            return seed
        }
    }
}
