name: "Publish APK/AAB to slack channel"
description: "Publish release, firebase, local or feature artifact to slack channel"

inputs:
  channel-id:
    required: true
    description: "Slack channel id"
  bot-token:
    required: true
    description: "Slack bot token"
  build-type:
    required: true
    description: "feature,release"
  artifact-type:
    required: true
    description: "apk,bundle"

runs:
  using: composite
  steps:
    - name: Curl upload file to slack POST request
      shell: bash
      run: |
        ls -R app/build/outputs/${{ inputs.artifact-type }}/${{ inputs.build-type }}
        apk_file=$(find app/build/outputs/${{ inputs.artifact-type }}/${{ inputs.build-type }} -name 'key-app*')
        apk_filename=$(basename "$apk_file")
        version_name=$(echo "$apk_filename" | sed 's/^key-app-\(.*\)$/\1/')
        
        curl \
        -F token="${{ inputs.bot-token }}" \
        -F text="Build $version_name is published!" \
        -F channels="${{ inputs.channel-id }}" \
        -F "file=@$apk_file" \
        https://slack.com/api/files.upload
