name: "Publish APK/Bundle to slack channel"
description: "Publish release or feature artifact to slack channel"
inputs:
  channel-id:
    required: true
    description: "Slack channel id"
  bot-token:
    required: true
    description: "Slack bot token"
  build-type:
    required: true
    description: "debug,feature,release"
  artifact-type:
    required: true
    description: "apk,bundle"

runs:
  using: composite
  steps:
    - name: Curl upload file to slack POST request
      shell: bash
      run: |
        ls -R app/build/outputs/${{ inputs.build-type }}/${{ inputs.artifact-type }}
        curl \
        -S -s -o /dev/null \
        -F token="${{ inputs.bot-token }}" \
        -F channels="${{ inputs.channel-id }}" \
        -F initial_comment="Hey! Here is a new feature apk. Success :tada:" \
        -F "file="@$(find app/build/outputs/${{ inputs.artifact-type }}/${{ outputs.build-type }} -name 'p2p*')" \
        https://slack.com/api/files.upload
