name: "Publish APK/Bundle to slack channel"
description: "Publish release or feature artifact to slack channel"
inputs:
  channel-id:
    required: true
    description: "Slack channel id"
  bot-token:
    required: true
    description: "Slack bot token"
  artifact:
    required: true
    description: "apk or aab file"

runs:
  using: composite
  steps:
    - name: Curl upload file to slack POST request
      shell: bash
      run: |
        curl \
        -S -s -o /dev/null \
        -F token="${{ inputs.bot-token }}" \
        -F channels="${{ inputs.channel-id }}" \
        -F initial_comment="Hey! Here is a new feature apk. Success :tada:" \
        -F "file=@$(${ inputs.artifact })" \
        https://slack.com/api/files.upload
