name: "Setup gradle"
description: "Setup all gradle dependencies and cache them to use next"
inputs:
  worker-name:
    required: false
    description: "Name of the worker"

runs:
  using: composite
  steps:
    - name: Setup gradle dependencies cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}

    - name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew