name: "Jira manipulations - REVIEW"
description: "When a pull request is created, moving the ticket number to REVIEW status in JIRA"
inputs:
  jira-base-url:
    description: "Jira base url"
    required: true
  jira-user-email:
    description: "Jira user email"
    required: true
    default: "chyngyz.i@p2p.org"
  jira-api-token:
    description: "Jira api token related to the jira-user-email"
    required: true

runs:
  using: composite
  steps:
    - name: "Login"
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-user-email }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}

    - name: "Find ticket number in from commits"
      id: review
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: branch

    - name: "Jira Ticket Transition"
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.review.outputs.issue }}
        transition: "REVIEW"