package org.p2p.wallet.home.api

import org.p2p.wallet.R
import org.p2p.wallet.home.model.TokenColor

object TokenColors {

    private val data = tokensColors()

    fun findColorBySymbol(symbol: String): Int {
        val token = data.firstOrNull { it.symbol == symbol }
        return token?.color ?: R.color.chartSOL
    }

    fun getSymbols() = data.map { it.symbol }

    private fun tokensColors() = mutableListOf(
        TokenColor(
            "SOL",
            R.color.chartSOL
        ),
        TokenColor(
            "MSRM",
            R.color.chartSRM
        ),
        TokenColor(
            "SRM",
            R.color.chartSRM
        ),
        TokenColor(
            "BTC",
            R.color.chartBTC
        ),
        TokenColor(
            "renBTC",
            R.color.chartBTC
        ),
        TokenColor(
            "ETH",
            R.color.chartETH
        ),
        TokenColor(
            "FTT",
            R.color.chartFTX
        ),
        TokenColor(
            "YFI",
            R.color.chartYFI
        ),
        TokenColor(
            "LINK",
            R.color.chartLINK
        ),
        TokenColor(
            "XRP",
            R.color.chartXRP
        ),
        TokenColor(
            "USDT",
            R.color.chartUSDT
        ),
        TokenColor(
            "USDC",
            R.color.chartUSDC
        ),
        TokenColor(
            "WUSDC",
            R.color.chartUSDC
        ),
        TokenColor(
            "SUSHI",
            R.color.chartSUSHI
        ),
        TokenColor(
            "ALEPH",
            R.color.chartALEPH
        ),
        TokenColor(
            "SXP",
            R.color.chartSXP
        ),
        TokenColor(
            "HGET",
            R.color.chartHGET
        ),
        TokenColor(
            "CREAM",
            R.color.chartCREAM
        ),
        TokenColor(
            "UBXT",
            R.color.chartUBXT
        ),
        TokenColor(
            "HNT",
            R.color.chartHNT
        ),
        TokenColor(
            "FRONT",
            R.color.chartFRONT
        ),
        TokenColor(
            "AKRO",
            R.color.chartAKRO
        ),
        TokenColor(
            "HXRO",
            R.color.chartHXRO
        ),
        TokenColor(
            "UNI",
            R.color.chartUNI
        ),
        TokenColor(
            "MATH",
            R.color.chartMATH
        ),
        TokenColor(
            "TOMO",
            R.color.chartTOMO
        ),
        TokenColor(
            "LUA",
            R.color.chartLUA
        ),
        TokenColor(
            "MSRM",
            R.color.chartSRM
        ),
        TokenColor(
            "KARMA",
            R.color.chartSOL
        ),
        TokenColor(
            "KEEP",
            R.color.chartSRM
        ),
        TokenColor(
            "SWAG",
            R.color.chartBTC
        ),
        TokenColor(
            "CEL",
            R.color.chartETH
        ),
        TokenColor(
            "RSR",
            R.color.chartFTX
        ),
        TokenColor(
            "1INCH",
            R.color.chartYFI
        ),
        TokenColor(
            "GRT",
            R.color.chartLINK
        ),
        TokenColor(
            "COMP",
            R.color.chartXRP
        ),
        TokenColor(
            "PAXG",
            R.color.chartUSDT
        ),
        TokenColor(
            "STRONG",
            R.color.chartUSDC
        ),
        TokenColor(
            "FIDA",
            R.color.chartUSDC
        ),
        TokenColor(
            "KIN",
            R.color.chartSUSHI
        ),
        TokenColor(
            "MAPS",
            R.color.chartALEPH
        ),
        TokenColor(
            "OXY",
            R.color.chartSXP
        ),
        TokenColor(
            "USDT",
            R.color.chartHGET
        ),
        TokenColor(
            "BRZ",
            R.color.chartCREAM
        ),
        TokenColor(
            "RAY",
            R.color.chartUBXT
        ),
        TokenColor(
            "PERK",
            R.color.chartHNT
        ),
        TokenColor(
            "BTSG",
            R.color.chartFRONT
        ),
        TokenColor(
            "BVOL",
            R.color.chartAKRO
        ),
        TokenColor(
            "IBVOL",
            R.color.chartHXRO
        ),
        TokenColor(
            "AAVE",
            R.color.chartUNI
        ),
        TokenColor(
            "LQID",
            R.color.chartMATH
        ),
        TokenColor(
            "SECO",
            R.color.chartTOMO
        ),
        TokenColor(
            "HOLY",
            R.color.chartLUA
        ),
        TokenColor(
            "SDOGE",
            R.color.chartSRM
        ),
        TokenColor(
            "SAMO",
            R.color.chartSOL
        ),
        TokenColor(
            "ISA",
            R.color.chartSRM
        ),
        TokenColor(
            "RECO",
            R.color.chartBTC
        ),
//        TokenColor(
//            "NINJA%20NFT1",
//            R.color.chartETH
//        ),
        TokenColor(
            "NINJA",
            R.color.chartFTX
        ),
        TokenColor(
            "SLIM",
            R.color.chartYFI
        ),
        TokenColor(
            "QUEST",
            R.color.chartLINK
        ),
        TokenColor(
            "SPD",
            R.color.chartXRP
        ),
        TokenColor(
            "STEP",
            R.color.chartUSDT
        ),
        TokenColor(
            "MEDIA",
            R.color.chartUSDC
        ),
        TokenColor(
            "SLOCK",
            R.color.chartUSDC
        ),
        TokenColor(
            "ROPE",
            R.color.chartSUSHI
        ),
        TokenColor(
            "DOCE",
            R.color.chartALEPH
        ),
        TokenColor(
            "MCAPS",
            R.color.chartSXP
        ),
        TokenColor(
            "COPE",
            R.color.chartHGET
        ),
        TokenColor(
            "XCOPE",
            R.color.chartCREAM
        ),
        TokenColor(
            "AAPE",
            R.color.chartUBXT
        ),
        TokenColor(
            "oDOP",
            R.color.chartHNT
        ),
        TokenColor(
            "RAYPOOL",
            R.color.chartFRONT
        ),
        TokenColor(
            "PERP",
            R.color.chartAKRO
        ),
        TokenColor(
            "OXYPOOL",
            R.color.chartHXRO
        ),
        TokenColor(
            "MAPSPOOL",
            R.color.chartUNI
        ),
        TokenColor(
            "TRYB",
            R.color.chartTOMO
        ),
        TokenColor(
            "ENTROPPP",
            R.color.chartTOMO
        ),
        TokenColor(
            "FARM",
            R.color.chartLUA
        ),
        TokenColor(
            "NOPE",
            R.color.chartSRM
        ),
        TokenColor(
            "STNK",
            R.color.chartSOL
        ),
        TokenColor(
            "MEAL",
            R.color.chartSRM
        ),
        TokenColor(
            "SNY",
            R.color.chartBTC
        ),
        TokenColor(
            "FROG",
            R.color.chartETH
        ),
        TokenColor(
            "CRT",
            R.color.chartFTX
        ),
        TokenColor(
            "SKEM",
            R.color.chartYFI
        ),
        TokenColor(
            "SOLAPE",
            R.color.chartLINK
        ),
        TokenColor(
            "WOOF",
            R.color.chartXRP
        ),
        TokenColor(
            "MER",
            R.color.chartUSDT
        ),
        TokenColor(
            "ACMN",
            R.color.chartUSDC
        ),
        TokenColor(
            "MUDLEY",
            R.color.chartUSDC
        ),
        TokenColor(
            "LOTTO",
            R.color.chartSUSHI
        ),
        TokenColor(
            "BOLE",
            R.color.chartALEPH
        ),
        TokenColor(
            "mBRZ",
            R.color.chartSXP
        ),
        TokenColor(
            "mPLAT",
            R.color.chartHGET
        ),
        TokenColor(
            "mDIAM",
            R.color.chartCREAM
        ),
        TokenColor(
            "APYS",
            R.color.chartUBXT
        ),
        TokenColor(
            "MIT",
            R.color.chartHNT
        ),
        TokenColor(
            "PAD",
            R.color.chartFRONT
        ),

        TokenColor(
            "SOLA",
            R.color.chartAKRO
        ),
        TokenColor(
            "SHBL",
            R.color.chartHXRO
        ),
        TokenColor(
            "AUSS",
            R.color.chartUNI
        ),
        TokenColor(
            "TULIP",
            R.color.chartMATH
        ),
        TokenColor(
            "JPYC",
            R.color.chartTOMO
        ),
        TokenColor(
            "TYNA",
            R.color.chartLUA
        ),
        TokenColor(
            "ARDX",
            R.color.chartAKRO
        ),
        TokenColor(
            "SSHIB",
            R.color.chartHXRO
        ),
        TokenColor(
            "SGI",
            R.color.chartUNI
        ),
        TokenColor(
            "SOLT",
            R.color.chartMATH
        ),
        TokenColor(
            "KEKW",
            R.color.chartTOMO
        ),
        TokenColor(
            "LOOP",
            R.color.chartLUA
        ),
        TokenColor(
            "BDE",
            R.color.chartAKRO
        ),
        TokenColor(
            "DWT",
            R.color.chartHXRO
        ),
        TokenColor(
            "DOGA",
            R.color.chartUNI
        ),
        TokenColor(
            "CHEEMS",
            R.color.chartMATH
        ),
        TokenColor(
            "SBFC",
            R.color.chartTOMO
        ),
        TokenColor(
            "ECOP",
            R.color.chartLUA
        ),
        TokenColor(
            "CATO",
            R.color.chartAKRO
        ),
        TokenColor(
            "TOM",
            R.color.chartHXRO
        ),
        TokenColor(
            "FABLE",
            R.color.chartUNI
        ),
        TokenColor(
            "LZD",
            R.color.chartMATH
        ),
        TokenColor(
            "FELON",
            R.color.chartTOMO
        ),
        TokenColor(
            "SLNDN",
            R.color.chartLUA
        ),
        TokenColor(
            "MPAD",
            R.color.chartHXRO
        ),
        TokenColor(
            "SGT",
            R.color.chartUNI
        ),
        TokenColor(
            "SOLDOG",
            R.color.chartTOMO
        ),
        TokenColor(
            "LLAMA",
            R.color.chartLUA
        ),
        TokenColor(
            "BOP",
            R.color.chartAKRO
        ),
        TokenColor(
            "MOLAMON",
            R.color.chartHXRO
        ),
        TokenColor(
            "STUD",
            R.color.chartUNI
        ),
        TokenColor(
            "RESP",
            R.color.chartMATH
        ),
        TokenColor(
            "CHAD",
            R.color.chartTOMO
        ),
        TokenColor(
            "DXL",
            R.color.chartLUA
        ),
        TokenColor(
            "FUZ",
            R.color.chartAKRO
        ),
        TokenColor(
            "STRANGE",
            R.color.chartHXRO
        ),
        TokenColor(
            "GRAPE",
            R.color.chartUNI
        ),
        TokenColor(
            "KERMIT",
            R.color.chartMATH
        ),
        TokenColor(
            "PIPANA",
            R.color.chartTOMO
        ),
        TokenColor(
            "CKC",
            R.color.chartLUA
        ),
        TokenColor(
            "CHANGPENGUIN",
            R.color.chartAKRO
        ),
        TokenColor(
            "KLB",
            R.color.chartHXRO
        )
    )
}