package org.p2p.solanaj.core

import org.bitcoinj.crypto.DeterministicHierarchy
import org.bitcoinj.crypto.HDKeyDerivation
import org.bitcoinj.crypto.HDUtils
import org.bitcoinj.crypto.MnemonicCode
import org.p2p.solanaj.crypto.DerivationPath
import org.p2p.solanaj.crypto.SolanaBip44
import org.p2p.solanaj.utils.TweetNaclFast

class Account {
    private var keyPair: TweetNaclFast.Signature.KeyPair

    constructor() {
        keyPair = TweetNaclFast.Signature.keyPair()
    }

    constructor(secretKey: ByteArray) {
        keyPair = TweetNaclFast.Signature.keyPair_fromSecretKey(secretKey)
    }

    private constructor(keyPair: TweetNaclFast.Signature.KeyPair) {
        this.keyPair = keyPair
    }

    val publicKey: PublicKey
        get() = PublicKey(keyPair.publicKey)

    val secretKey: ByteArray
        get() = keyPair.secretKey

    companion object {
        /**
         * Derive a Solana account from a Mnemonic generated by the Solana CLI using bip32 Mnemonic with deviation path of
         * m/501H/0H/0/0
         * @param words seed words
         * @param passphrase seed passphrase
         * @return Solana account
         */
        fun fromBip32Mnemonic(words: List<String>, walletIndex: Int, passphrase: String = ""): Account {
            val seed = MnemonicCode.toSeed(words, passphrase)
            val masterPrivateKey = HDKeyDerivation.createMasterPrivateKey(seed)
            val deterministicHierarchy = DeterministicHierarchy(masterPrivateKey)
            val child = deterministicHierarchy[HDUtils.parsePath("M/501H/${walletIndex}H/0/0"), true, true]
            val keyPair = TweetNaclFast.Signature.keyPair_fromSeed(child.privKeyBytes)
            return Account(keyPair)
        }

        /**
         * Derive a Solana account from a Mnemonic generated by the Solana CLI using bip44 Mnemonic with deviation path of
         * m/44H/501H/0H
         * @param words seed words
         * @param passphrase seed passphrase
         * @return Solana account
         */
        fun fromBip44Mnemonic(words: List<String>, walletIndex: Int, passphrase: String = ""): Account {
            val solanaBip44 = SolanaBip44(walletIndex)
            val seed = MnemonicCode.toSeed(words, passphrase)
            val privateKey: ByteArray = solanaBip44.getPrivateKeyFromSeed(seed, DerivationPath.BIP44)
            return Account(TweetNaclFast.Signature.keyPair_fromSeed(privateKey))
        }

        /**
         * Derive a Solana account from a Mnemonic generated by the Solana CLI using bip44 Mnemonic with deviation path of
         * m/44H/501H/0H/0H
         * @param words seed words
         * @param passphrase seed passphrase
         * @return Solana account
         */
        fun fromBip44MnemonicWithChange(words: List<String>, walletIndex: Int, passphrase: String = ""): Account {
            val solanaBip44 = SolanaBip44(walletIndex)
            val seed = MnemonicCode.toSeed(words, passphrase)
            val privateKey: ByteArray = solanaBip44.getPrivateKeyFromSeed(seed, DerivationPath.BIP44CHANGE)
            return Account(TweetNaclFast.Signature.keyPair_fromSeed(privateKey))
        }
    }
}
