name: "Setup version build"
description: "Generating a unique version build in app/gradle.properties"

runs:
  using: composite
  steps:
    - name: Setup version
      shell: bash
      run: |
        # Get the number of commits in the repository
        commit_count=$(git rev-list --count HEAD)
        
        # Combine the timestamp with the GITHUB_RUN_NUMBER
        version=$commit_count
        
        # Set the version build number using the unique identifier
        ./gradlew setVersionBuild -Pversion=$version
        echo "Set build version to ${version}"