name: "Create analytics properties file"
description: "Create analytics.properties and fill them"
inputs:
  amplitude-secret-debug:
    description: "Amplitude api key - DEBUG"
    required: true
  amplitude-secret-release:
    description: "Amplitude api key - RELEASE"
    required: true

runs:
  using: composite
  steps:
    - name: Create analytics.properties file
      shell: bash
      run: |
        touch analytics.properties
        echo "amplitudeDebugKey=\"${{ inputs.amplitude-secret-debug }}\"" >> analytics.properties
        echo "amplitudeReleaseKey=\"${{ inputs.amplitude-secret-release }}\"" >> analytics.properties
        echo "analytics.properties successfully created"