name: "Setup Sentry"
description: "Create sentry file for Github Action"
inputs:
  default-project:
    description: "Project name for Sentry"
    required: false
    default: "android"
  default-organization:
    description: "Project organization for Sentry"
    required: false
    default: "p2p-wallet"
  default-url:
    description: "Project Sentry full URL"
    required: false
    default: "https://sentry.io/"
  auth-token:
    description: "Project Sentry Auth Token"
    required: true
  auth-dsn:
    description: "Project Sentry DSN"
    required: true

runs:
  using: composite
  steps:
    - name: Create sentry.properties file
      shell: bash
      run: |
        touch sentry.properties
        echo "defaults.project=${{ inputs.default-project }}" >> sentry.properties
        echo "defaults.org=${{ inputs.default-organization }}" >> sentry.properties
        echo "defaults.url=${{ inputs.default-url }}" >> sentry.properties
        echo "auth.token=${{ inputs.auth-token }}" >> sentry.properties
        echo "auth.dsn=${{ inputs.auth-dsn }}" >> sentry.properties