name: "Setup all needed files and properties for project"
description: "-"
inputs:
  firebase-secret:
    description: "Firebase secret"
    required: true
  ssl-certificate:
    description: "SSL certificate"
    required: true
  keystore-secret:
    description: "Release JKS keystore"
    required: true
runs:
  using: composite
  steps:
    - name: "Create Firebase google-services.json"
      uses: ./.github/actions/setup-firebase
      with:
        firebase-secret: ${{ inputs.firebase-secret }}
    - name: "Create cert.pem file"
      env:
        SSL_CERTIFICATE: ${{ inputs.ssl-certificate }}
      shell: bash
      run: echo $SSL_CERTIFICATE -> app/src/main/res/raw/cert.pem
    - name: "Create keystore .jks"
      uses: ./.github/actions/setup-keystore-jks
      with:
        keystore-secret: ${{ inputs.keystore-secret }}

    - name: "Setup gradle"
      uses: ./.github/actions/setup-gradle