name: "Jira manipulations - READY FOR TESTING"
description: "When a feature build is uploaded to Firebase&Slack, moving the ticket number to RFT status in JIRA"
inputs:
  jira-base-url:
    description: "Jira base url"
    required: true
  jira-api-token:
    description: "Jira api token related to the jira-user-email"
    required: true

runs:
  using: composite
  steps:
    - name: "Extract JIRA key from commit message"
      shell: bash
      id: find-jira-ticket
      run: |
        jira_ticket=$(./bash_scripts/find_jira_key.sh)
        echo "JIRA Ticket: $jira_ticket"
      env:
        jira-ticket: ${{ steps.find-jira-ticket.outputs.jira_ticket }}
    - name: Update JIRA issue status
      shell: bash
      if: env.jira-ticket
      run: |
        curl -D- -H "Authorization: Basic ${{ inputs.jira-api-token }}" \
          -X PUT \
          -H "Content-Type: application/json" \
          -d '{"fields": {"status": {"name": "Ready for Testing"}}}' \
          https://${{ inputs.jira-base-url }}/rest/api/2/issue/${{ env.jira-ticket }}