name: "Setup keystore file"
description: "Create jks file"
inputs:
  keystore-secret:
    required: true
    description: "jks keystore secret"
  keystore-password:
    required: true
    description: "jks keystore password"
  key-alias:
    required: true
    description: "jks key alias"
  key-password:
    required: true
    description: "jks key password"
  keystore-path:
    required: false
    description: "jks file path"
    default: "p2pwallet.jks"


runs:
  using: composite
  steps:
    - name: Create p2p-wallet.jks
      shell: bash
      run: |
        printf "%s" "${{ inputs.keystore-secret }}" -> p2pwallet.jks
        touch signing.properties
        echo "keystorePath=\"${{ inputs.keystore-path }}\"" >> signing.properties
        echo "keystorePassword=\"${{ inputs.keystore-password }}\"" >> signing.properties
        echo "keystoreAlias=\"${{ inputs.key-alias }}\"" >> signing.properties
        echo "keyPassword=\"${{ inputs.key-password }}\"" >> signing.properties

