name: "Setup keystore file"
description: "Create jks file"
inputs:
  keystore-secret:
    required: true
    description: "Raw value jks"
  keystore-phrase:
    required: true
    description: "Keystore GPG key passphrase"

runs:
  using: composite
  steps:
    - name: Create p2p-wallet.jks
      shell: bash
      run: |
        echo ${{ inputs.keystore-secret }} -> p2p-wallet.asc
        gpg -d --passphrase "${{ inputs.keystore-phrase }}" --batch p2p-wallet.asc > p2p-wallet.jks
