name: "Setup keystore file"
description: "Create jks file"
inputs:
  keystore_secret:
    required: true
    description: "Raw value jks"
  keystore_passphrase:
    required: true
    description: "Keystore GPG key passphrase"

runs:
  using: composite
  steps:
    - name: Create p2p-wallet.jks
      shell: bash
      env:
        KEYSTORE_SECRET: ${{ inputs.keystore_secret }}
      run: |
        echo $KEYSTORE_SECRET -> p2p-wallet.asc
        gpg -d --passphrase ${{ inputs.keystore-passphrase }} --batch p2p-wallet.jks.asc > p2p-wallet.jks
