name: "Setup keystore file"
description: "Create jks file"
inputs:
  keystore_secret:
    required: true
    description: "Raw value jks"
  keystore_phrase:
    required: true
    description: "Keystore GPG key passphrase"

runs:
  using: composite
  steps:
    - name: Create p2p-wallet.jks
      shell: bash
      run: |
        echo ${{ inputs.keystore_secret }} -> p2p-wallet.asc
        gpg -d --passphrase "${{ inputs.keystore_phrase }}" --batch p2p-wallet.asc > p2p-wallet.jks
~