name: Android build feature artifacts [APK,AAB]

on: [ pull_request ]

jobs:
  build-apk-feature:
    runs-on: ubuntu-latest
    name: Build Feature APK
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: ./.github/actions/setup-firebase
        with:
          firebase-secret: ${{ secrets.GOOGLE_SERVICE_JSON_SECRET }}

      - name: Create apikey file
        uses: ./.github/actions/setup-apikey
        with:
          rpc-pool-secret: ${{ secret.RPC_POOL_API_KEY }}
          moonpay-secret: ${{ secret.MOONPAY_KEY }}
          compare-secret: ${{ secret.COMPARE_PUBLIC_KEY }}
          intercom-id-secret: ${{ secret.INTERCOM_APP_ID }}
          intercom-key-secret: ${{ secret.INTERCOM_API_KEY }}
          amplitude-secret: ${{ secret.AMPLITUDE_KEY }}

      - name: Upload artifact to Firebase
        run: ./gradlew assembleFeature appDistributionUploadFeature

      - name: Upload artifact to Slack
        uses: ./.github/actions/setup-slack
        with:
          aritfact: app/build/outputs/apk/feature/*.apk
          bot-token: ${{ secret.SLACK_BOT_TOKEN }}
          channel-id: ${{ secret.SLACK_CHANNEL_ID }}







