name: Android build feature artifacts [APK,AAB]

on:
  pull_request:
    branches:
      - develop

jobs:
  Build-Feature-APK:
    runs-on: ubuntu-latest
    name: Build Feature APK
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Output version code
        run: echo VERSION_CODE

      - name: Create apikey properties file
        run: |
          - echo "rpcPoolApiKey=\"${{ secrets.RPC_POOL_API_KEY }}\"" > apikey.properties
          - echo "moonpayKey=\"${{ secrets.MOONPAY_KEY }}\"" >> apikey.properties
          - echo "comparePublicKey=\"${{ secrets.COMPARE_PUBLIC_KEY }}\"" >> apikey.properties
          - echo "intercomApiKey=\"${{ secrets.INTERCOM_API_KEY }}\"" >> apikey.properties
          - echo "intercomAppId=\"${{ secrets.INTERCOM_APP_ID }}\"" >> apikey.properties
          - echo "amplitudeKey=\"${{ secrets.AMPLITUDE_KEY }}\"" >> apikey.properties
          - echo "apikeys.properties succesfully created"

      - name: Setup google-json from secrets
        env:
          FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICE_JSON_SECRET }}
        run: echo $FIREBASE_SECRET > app/google-services.json

      - name: Create and fill cert.pem certificate for SSL pinning
        env:
          SSL_CERTIFICATE: ${{ secrets.SSL_CERTIFICATE }}
        run: echo $SSL_CERTIFICATE -> app/src/main/res/raw/cert.pem

      - name: Build feature artifacts with gradle
        run: ./gradlew assembleFeature






