on:
  push:
    branches:
      - feature/*
jobs:
  update-jira-status:
    name: "Authorize in Jira"
      runs-on: ubuntu-latest
      steps:
        - name: "Login"
          uses: atlassian/gajira-login@v3
          env:
            JIRA_BASE_URL: https://p2pvalidator.atlassian.net
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: "Find ticket number in git history"
          id: review
          uses: atlassian/gajira-find-issue-key@v3
          with:
            from: commits

        - name: "Jira Ticket Transition"
          uses: atlassian/gajira-transition@v3
          with:
            issue: ${{ steps.review.outputs.issue }}
            transition: "REVIEW"

  android-lint:
    name: "Run ktlint check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Initialize project keys"
        uses: ./.github/actions/setup-project
        with:
          firebase-secret: ${{ secrets.GOOGLE_SERVICE_JSON_SECRET }}
          torus-verifier-debug: ${{ secrets.TORUS_VERIFIER_DEBUG }}
          torus-verifier-feature: ${{ secrets.TORUS_VERIFIER_FEATURE }}
          torus-verifier-release: ${{ secrets.TORUS_VERIFIER_RELEASE }}
          torus-subverifier-store: ${{ secrets.TORUS_SUB_VERIFIER_RELEASE_STORE }}
          torus-subverifier-firebase: ${{ secrets.TORUS_SUB_VERIFIER_RELEASE_FIREBASE }}
          torus-subverifier-local: ${{ secrets.TORUS_SUB_VERIFIER_RELEASE_LOCAL }}
          rpc-pool-secret: ${{ secrets.RPC_POOL_API_KEY }}
          moonpay-secret: ${{ secrets.MOONPAY_KEY }}
          moonpay-sandbox-secret: ${{ secrets.MOONPAY_SANDBOX_KEY }}
          compare-secret: ${{ secrets.COMPARE_PUBLIC_KEY }}
          intercom-id-secret: ${{ secrets.INTERCOM_APP_ID }}
          intercom-key-secret: ${{ secrets.INTERCOM_API_KEY }}
          amplitude-secret: ${{ secrets.AMPLITUDE_KEY }}
          apps-flyer-secret: ${{ secrets.APPS_FLYER_KEY }}
          auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          auth-dsn: ${{ secrets.SENTRY_AUTH_DSN }}
          ssl-certificate: ${{ secrets.SSL_CERTIFICATE }}
          keystore-secret: ${{ secrets.KEYSTORE_SECRET }}
      - name: Run ktlint
        run: ./gradlew ktlint -PautoCorrect=0
